. "c:\Users\786\Desktop\kam\_common.ps1"

# Topic and profession blogs using single-quoted here-strings

function MkTopic($slug, $title, $desc, $kw, $cat, $icon, $rt, $lead, $body) {
    $html = MkPage $slug $title $desc $kw "https://kambohassociates.com/blogs/$slug" $cat $icon $title $rt $lead $body
    WB $slug $html
}

# 1
$b = @'
<h2>Step 1 - Get Your NTN</h2><p>Before filing, you need an NTN. If you do not have one, WhatsApp 0328-4675162. We register NTN same day for Rs. 2,000.</p><h2>Step 2 - Login to FBR IRIS</h2><p>Go to iris.fbr.gov.pk and login with your NTN and password. First time login requires password reset via registered mobile number.</p><h2>Step 3 - Gather Your Documents</h2><ul><li>CNIC copy</li><li>Salary slips or employer tax certificate</li><li>Bank statement for the tax year (July to June)</li><li>Details of any property owned or sold</li><li>Business income records if applicable</li></ul><h2>Step 4 - Fill Income Tax Return on IRIS</h2><ul><li>Go to Returns section on IRIS</li><li>Select Tax Year 2026 (July 2025 to June 2026)</li><li>Fill in income details under relevant heads</li><li>Declare tax already deducted (WHT)</li><li>Complete wealth statement and submit</li></ul><h2>Step 5 - Pay Any Remaining Tax</h2><p>If tax liability exceeds WHT already paid, generate a payment challan (PSID) and pay via internet banking before deadline.</p><div class='highlight-box'><p><strong>Too complicated?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> and we file for you. Rs. 3,500 all-inclusive, same day.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>What is the income tax return deadline for 2026? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>September 30, 2026 for individuals. FBR often extends deadlines so check fbr.gov.pk for updates.</div></div><div class='faq-item'><div class='faq-q'>Can I file return without an accountant? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Yes but errors in wealth reconciliation often lead to FBR notices. A tax consultant for Rs. 3,500 ensures correct filing and no audit risk.</div></div></div>
'@
MkTopic "how-to-file-income-tax-return-pakistan-2026" "How to File Income Tax Return Pakistan 2026 - Step by Step Guide" "Step-by-step guide to filing income tax return in Pakistan 2026 on FBR IRIS portal." "how to file income tax return Pakistan 2026, FBR IRIS filing guide, income tax filing steps Pakistan" "Tax Guides" "fas fa-list-check" "8 min read" "File your income tax return on FBR IRIS in 2026 with this complete step-by-step guide. Documents, process, and tips for salaried persons and business owners in Pakistan." $b

# 2
$b = @'
<h2>Salary Tax Slabs 2026</h2><table><tr><th>Annual Salary</th><th>Tax</th></tr><tr><td>Up to Rs. 600,000</td><td>0%</td></tr><tr><td>Rs. 600,001 - 1,200,000</td><td>5% above Rs. 600,000</td></tr><tr><td>Rs. 1,200,001 - 2,200,000</td><td>Rs. 30,000 + 15% above Rs. 1,200,000</td></tr><tr><td>Rs. 2,200,001 - 3,200,000</td><td>Rs. 180,000 + 25% above Rs. 2,200,000</td></tr><tr><td>Over Rs. 3,200,000</td><td>Rs. 430,000 + 30% above Rs. 3,200,000</td></tr></table><h2>Salary Components and Tax Treatment</h2><ul><li>Basic salary - fully taxable</li><li>House rent allowance - exempt up to 45% of basic salary</li><li>Medical allowance - exempt up to 10% of basic salary</li><li>Conveyance allowance - exempt up to Rs. 2,400/month</li><li>Bonus - taxable as salary income</li></ul><div class='highlight-box'><p><strong>Employer deducting wrong tax?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - we calculate your exact tax liability and help you claim any excess deducted.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Do I need to file a return if employer deducts tax? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Yes if your annual income exceeds Rs. 600,000 or you have other income sources. Filing the return is what gives you filer status on ATL.</div></div></div>
'@
MkTopic "tax-on-salary-pakistan-2026" "Income Tax on Salary in Pakistan 2026 - Calculation Guide" "How is income tax calculated on salary in Pakistan 2026? Tax slabs, exemptions, allowances, and how to calculate your monthly tax deduction." "salary tax Pakistan 2026, income tax on salary Pakistan, salary tax slabs 2026" "Tax Guides" "fas fa-money-check-alt" "6 min read" "Know exactly how much income tax your employer should deduct from your salary every month in Pakistan 2026. Tax slabs, exemptions, and deductions explained." $b

# 3
$b = @'
<h2>What is Minimum Tax Section 113?</h2><p>Section 113 requires businesses to pay a minimum tax of 1.25% of turnover (gross revenue) if their regular income tax is less than this amount. This prevents businesses from reporting zero or very low tax through excessive deductions.</p><h2>Minimum Tax Rates 2026</h2><table><tr><th>Category</th><th>Minimum Tax Rate</th></tr><tr><td>General businesses</td><td>1.25% of turnover</td></tr><tr><td>Distributors of FMCG</td><td>0.25% of turnover</td></tr><tr><td>Flour and sugar mills</td><td>0.25% of turnover</td></tr><tr><td>Oil marketing companies</td><td>0.5% of turnover</td></tr></table><h2>How Minimum Tax Works</h2><p>Calculate your regular income tax first. If it is less than 1.25% of your turnover, you pay the minimum tax instead. Excess minimum tax over regular tax can be carried forward for 5 years.</p><div class='highlight-box'><p><strong>Business tax compliance?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - we handle all FBR compliance for your business.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Can minimum tax be refunded? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>No, minimum tax is not refundable but excess over regular tax can be carried forward for 5 years to offset future tax liability.</div></div></div>
'@
MkTopic "minimum-tax-section-113-pakistan" "Minimum Tax Section 113 Pakistan 2026 - Who Pays and How" "Guide to minimum tax under Section 113 of Income Tax Ordinance in Pakistan. Who must pay, how to calculate, and how it differs from regular income tax." "minimum tax section 113 Pakistan, turnover tax Pakistan 2026, minimum tax rate Pakistan" "Tax Guides" "fas fa-calculator" "6 min read" "Minimum tax under Section 113 applies to companies and individuals with business income whose regular tax is below the minimum threshold. Know if it applies to you." $b

# 4
$b = @'
<h2>What is Super Tax?</h2><p>Super tax is an additional income tax levied on high-income individuals and companies under Section 4C of the Income Tax Ordinance 2001. Introduced to raise revenue from the highest earners.</p><h2>Super Tax Rates 2026</h2><table><tr><th>Annual Income</th><th>Super Tax Rate</th></tr><tr><td>Rs. 150M - 200M</td><td>1%</td></tr><tr><td>Rs. 200M - 250M</td><td>2%</td></tr><tr><td>Rs. 250M - 300M</td><td>3%</td></tr><tr><td>Rs. 300M - 350M</td><td>4%</td></tr><tr><td>Over Rs. 350M</td><td>10%</td></tr></table><div class='highlight-box'><p><strong>Large business tax compliance?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - corporate tax specialists at your service.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Is super tax in addition to regular income tax? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Yes. Super tax is charged on top of regular income tax and minimum tax. Total effective tax rate for large companies can reach 39% or more.</div></div></div>
'@
MkTopic "super-tax-pakistan-2026" "Super Tax Pakistan 2026 - Who Pays and What Rate" "Guide to super tax in Pakistan 2026. Who is liable, applicable rates on high-income earners and companies, and how to calculate and pay super tax." "super tax Pakistan 2026, Section 4C income tax, super tax rate Pakistan" "Tax Guides" "fas fa-arrow-up" "5 min read" "Super tax is an additional levy on high-income individuals and large corporations in Pakistan. Know if you are liable and what rate applies in 2026." $b

# 5
$b = @'
<h2>Tax on Bank Profit Rates 2026</h2><table><tr><th>Status</th><th>WHT Rate</th><th>Tax Type</th></tr><tr><td>Active Filer</td><td>15%</td><td>Final tax</td></tr><tr><td>Non-Filer</td><td>30%</td><td>Final tax</td></tr></table><h2>What Counts as Bank Profit?</h2><ul><li>Interest on savings accounts</li><li>Profit on term deposits (TDRs)</li><li>Profit on National Savings certificates</li><li>Profit on current accounts if interest bearing</li></ul><h2>How Bank Deducts WHT</h2><p>Banks automatically deduct WHT every 6 months (June and December) before crediting profit to your account. Bank issues a tax deduction certificate which you need for your return.</p><div class='highlight-box'><p><strong>Need help with bank profit declaration?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - we optimize your tax return to minimize tax on savings.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Should I declare bank profit in tax return if WHT already deducted? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Yes. You must declare all bank profit in your return even if WHT is already deducted. You can either keep it as final tax or opt for normal regime if beneficial.</div></div></div>
'@
MkTopic "tax-on-bank-profit-pakistan-2026" "Tax on Bank Profit in Pakistan 2026 - Savings Account Interest Tax" "How is bank profit (interest on savings) taxed in Pakistan 2026? WHT rates for filers and non-filers, how to declare in tax return, and refund options." "bank profit tax Pakistan 2026, WHT on bank interest Pakistan, savings account tax Pakistan" "Tax Guides" "fas fa-piggy-bank" "5 min read" "Banks deduct withholding tax on profit/interest credited to your account every six months. Filers pay 15%, non-filers pay 30%. Know how to declare it correctly." $b

# 6
$b = @'
<h2>Key Benefits of Being an Active Filer</h2><table><tr><th>Transaction</th><th>Filer Rate</th><th>Non-Filer Rate</th><th>Saving</th></tr><tr><td>Property sale WHT</td><td>3%</td><td>6%</td><td>50%</td></tr><tr><td>Property purchase WHT</td><td>3%</td><td>6%</td><td>50%</td></tr><tr><td>Bank profit tax</td><td>15%</td><td>30%</td><td>50%</td></tr><tr><td>Vehicle registration (1000cc)</td><td>2%</td><td>4%</td><td>50%</td></tr><tr><td>Cash withdrawal over 50K</td><td>0%</td><td>0.6%</td><td>100%</td></tr><tr><td>Dividend income</td><td>15%</td><td>30%</td><td>50%</td></tr></table><h2>How to Become an Active Filer</h2><ul><li>Step 1: Get NTN registered (Rs. 2,000 via WhatsApp)</li><li>Step 2: File income tax return for current year</li><li>Step 3: Your name appears on ATL within 24-48 hours</li><li>Step 4: Check status at fbr.gov.pk or SMS CNIC to 9966</li></ul><div class='highlight-box'><p><strong>Become a filer today.</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - NTN + first return from Rs. 5,000. Start saving immediately.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>How long does it take to become a filer? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>After filing your return, ATL status updates within 24-48 hours. If you file before the ATL update date (March 1 each year), you are on the list for the full year.</div></div></div>
'@
MkTopic "filer-benefits-pakistan-2026" "Filer Benefits in Pakistan 2026 - Why You Must Become Active Filer" "Complete list of benefits for active filers in Pakistan 2026. Lower WHT on property, bank, vehicles. No cash withdrawal tax." "filer benefits Pakistan 2026, active filer benefits, ATL benefits Pakistan" "Tax Guides" "fas fa-star" "6 min read" "Being an active filer on FBR ATL list saves you money on every major transaction in Pakistan. Here are all the filer benefits in 2026 and how much you save." $b

# 7
$b = @'
<h2>Financial Penalties for Non-Filers</h2><table><tr><th>Consequence</th><th>Amount</th></tr><tr><td>Late filing penalty</td><td>Rs. 1,000 per week or 0.1% of tax per day</td></tr><tr><td>Property sale WHT</td><td>6% (filer pays 3%)</td></tr><tr><td>Property purchase WHT</td><td>6% (filer pays 3%)</td></tr><tr><td>Bank profit tax</td><td>30% (filer pays 15%)</td></tr><tr><td>Vehicle registration WHT</td><td>4-6% (filer pays 2%)</td></tr><tr><td>Cash withdrawal tax</td><td>0.6% over Rs. 50,000 (filer pays 0%)</td></tr></table><h2>Legal Consequences</h2><ul><li>FBR Section 114(4) notice requiring you to file</li><li>Prosecution under Section 191 - up to 1 year imprisonment</li><li>Bank accounts can be frozen in extreme cases</li><li>Cannot get government contracts or tenders</li></ul><div class='highlight-box'><p><strong>Not a filer yet?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - we file your return and make you active filer from Rs. 3,500.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Can FBR take action if I never filed? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Yes. FBR has access to property registrar, NADRA, bank, and CNIC data. If they identify you as a required filer, they issue notice and demand return plus penalty. Filing proactively is always safer.</div></div></div>
'@
MkTopic "non-filer-consequences-pakistan-2026" "Consequences of Not Filing Tax Return in Pakistan 2026" "What happens if you do not file income tax return in Pakistan 2026? Penalties, higher withholding tax, FBR notices, and travel restrictions for non-filers." "non-filer penalties Pakistan 2026, consequences not filing tax Pakistan, FBR non-filer" "Tax Guides" "fas fa-exclamation-triangle" "6 min read" "Not filing your income tax return in Pakistan has serious financial and legal consequences in 2026. Know the penalties and extra taxes non-filers pay on every transaction." $b

# 8
$b = @'
<h2>FBR Position on Cryptocurrency</h2><p>As of 2026, FBR treats cryptocurrency gains as capital gains income taxable under Section 37A of the Income Tax Ordinance. Crypto must be declared in wealth statement at current market value.</p><h2>Tax on Crypto Gains 2026</h2><table><tr><th>Holding Period</th><th>Rate</th></tr><tr><td>Under 12 months</td><td>15% CGT</td></tr><tr><td>Over 12 months</td><td>0%</td></tr></table><h2>What to Declare</h2><ul><li>Total crypto holdings in wealth statement at year-end value (in PKR)</li><li>Capital gains from crypto sold during the year</li><li>Mining income as business income</li></ul><div class='highlight-box'><p><strong>Have crypto holdings?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - we help you correctly declare crypto in your return.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Is crypto legal in Pakistan? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Crypto trading is in a grey area. SBP has restrictions but FBR requires declaration of crypto holdings for tax purposes. Declare your holdings to stay compliant.</div></div></div>
'@
MkTopic "tax-on-cryptocurrency-pakistan-2026" "Tax on Cryptocurrency in Pakistan 2026 - Bitcoin and Crypto Tax Guide" "How is cryptocurrency taxed in Pakistan in 2026? Capital gains on Bitcoin and crypto, declaration in wealth statement, and FBR stance on crypto income." "cryptocurrency tax Pakistan 2026, Bitcoin tax Pakistan, crypto tax FBR" "Tax Guides" "fas fa-bitcoin-sign" "6 min read" "FBR requires declaration of cryptocurrency holdings in wealth statement and taxes crypto gains as capital gains income. Know your obligations as a crypto holder in Pakistan." $b

# 9
$b = @'
<h2>WHT on Foreign Remittances 2026</h2><table><tr><th>Type</th><th>WHT Rate</th></tr><tr><td>Remittances received via banking channel</td><td>0% (exempt)</td></tr><tr><td>Freelance income from IT/digital services</td><td>1% (adjustable)</td></tr><tr><td>Foreign salary income</td><td>Taxable at normal slabs</td></tr></table><h2>Exemptions for Overseas Pakistanis</h2><ul><li>Remittances sent home by overseas Pakistanis are exempt from income tax for the recipient</li><li>Roshan Digital Account profit is taxed at reduced rates</li><li>Foreign earned income of non-resident Pakistanis is exempt from Pakistan tax</li></ul><h2>IT Freelancer Export Income</h2><p>Freelancers earning from foreign clients get 1% WHT on remittances received. This is adjustable against annual tax liability.</p><div class='highlight-box'><p><strong>Receiving foreign income?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - we optimize your tax for foreign remittances and freelance income.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Do I pay tax on money received from family abroad? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>No. Personal remittances from family members abroad are exempt from income tax. However, declare large amounts in wealth statement as source of funds.</div></div></div>
'@
MkTopic "tax-on-foreign-remittance-pakistan-2026" "Tax on Foreign Remittance in Pakistan 2026 - Overseas Income Guide" "How is foreign remittance taxed in Pakistan 2026? WHT on remittances, exemptions for overseas Pakistanis, and how to declare in income tax return." "foreign remittance tax Pakistan 2026, overseas income Pakistan tax, remittance WHT" "Tax Guides" "fas fa-globe" "6 min read" "Foreign remittances received in Pakistan from overseas employment or freelance work have specific tax treatment. Know your WHT obligations and exemptions in 2026." $b

# 10
$b = @'
<h2>Major Income Tax Exemptions in Pakistan 2026</h2><table><tr><th>Exemption</th><th>Condition</th></tr><tr><td>Agricultural income</td><td>100% exempt from federal income tax</td></tr><tr><td>Foreign remittances</td><td>Exempt if received via banking channel</td></tr><tr><td>Gratuity from approved fund</td><td>Up to Rs. 7.5 million exempt</td></tr><tr><td>Pension income</td><td>Exempt up to Rs. 1.2 million per year</td></tr><tr><td>Capital gains on property (over 5 years)</td><td>100% exempt</td></tr><tr><td>Scholarship income</td><td>100% exempt</td></tr></table><div class='highlight-box'><p><strong>Check if your income is exempt.</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - free tax consultation to review your specific situation.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Is agricultural income really tax free? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>From federal income tax yes. But provincial agricultural income tax applies in all four provinces. Also, non-agricultural income of a farmer is still taxable at normal rates.</div></div></div>
'@
MkTopic "income-tax-exemptions-pakistan-2026" "Income Tax Exemptions in Pakistan 2026 - What is Exempt from Tax" "Complete list of income tax exemptions in Pakistan 2026. Which income, persons, and transactions are exempt from FBR income tax." "income tax exemptions Pakistan 2026, tax exempt income Pakistan, what is exempt from tax Pakistan" "Tax Guides" "fas fa-shield" "6 min read" "Not all income in Pakistan is taxable. Know what is exempt from income tax in 2026 - agricultural income, remittances, pensions, gratuity, and more." $b

# 11
$b = @'
<h2>Top Tax Planning Strategies 2026</h2><ul><li><strong>Maximize deductible donations:</strong> Donate to approved charities (Section 61) and get up to 30% of taxable income as deduction</li><li><strong>Hold property over 5 years:</strong> Capital gains tax drops to 0% if property held over 5 years</li><li><strong>Use tax year timing:</strong> Pakistan tax year is July to June. Plan large transactions accordingly</li><li><strong>Separate business structure:</strong> Pvt Ltd company tax rate (29%) may be lower than personal slab for high earners</li><li><strong>Legitimate expense deductions:</strong> All genuine business expenses reduce taxable profit - keep all receipts</li></ul><h2>Deductions Available to Individuals</h2><ul><li>Zakat paid - deductible from taxable income</li><li>Charitable donations to approved organizations (up to 30% of income)</li><li>Worker Welfare Fund contributions</li></ul><div class='highlight-box'><p><strong>Want to reduce your tax legally?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - our tax planning consultation is free for new clients.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Is tax planning legal in Pakistan? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Yes. Tax planning (using legal provisions to minimize tax) is perfectly legal. Tax evasion (hiding income or false declarations) is illegal. All strategies above are within FBR rules.</div></div></div>
'@
MkTopic "tax-planning-tips-pakistan-2026" "Tax Planning Tips for Pakistan 2026 - How to Legally Reduce Tax" "Legal tax planning strategies for Pakistan 2026. How to reduce income tax through deductions, investments, timing, and structure." "tax planning Pakistan 2026, how to reduce income tax Pakistan, legal tax saving Pakistan" "Tax Guides" "fas fa-lightbulb" "7 min read" "Smart tax planning can legally reduce your tax liability in Pakistan 2026. Use deductions, investment schemes, timing strategies, and correct income structuring." $b

# 12
$b = @'
<h2>Types of FBR Tax Audits</h2><table><tr><th>Audit Type</th><th>How Selected</th></tr><tr><td>Random Audit</td><td>Computer-based random selection</td></tr><tr><td>Risk-Based Audit</td><td>FBR flags unusually low tax or wealth inconsistency</td></tr><tr><td>Sectoral Audit</td><td>All taxpayers in a specific industry</td></tr></table><h2>Common Audit Triggers</h2><ul><li>Large unexplained wealth increase year on year</li><li>High lifestyle expenses vs declared income</li><li>Large property or vehicle purchase without sufficient income</li><li>Significant WHT credits not matching income level</li></ul><h2>How to Prepare for an FBR Audit</h2><ul><li>Keep all bank statements for 6 years</li><li>Maintain all purchase and sale documents for properties</li><li>Keep business books, invoices, and expense receipts</li><li>Reconcile wealth statement year on year</li></ul><div class='highlight-box'><p><strong>Received an audit notice?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> immediately. We represent you before FBR and handle the entire audit process.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>How long does FBR audit take? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Simple audits complete in 30-60 days. Complex cases involving large businesses can take 6-12 months. Having a tax consultant represent you speeds up the process significantly.</div></div></div>
'@
MkTopic "fbr-audit-pakistan-2026" "FBR Tax Audit in Pakistan 2026 - How to Prepare and Respond" "What is FBR income tax audit in Pakistan? Types of audit, how to prepare, documents required, and how a tax consultant helps you survive a tax audit." "FBR audit Pakistan 2026, income tax audit Pakistan, how to handle FBR audit" "Tax Guides" "fas fa-search" "7 min read" "FBR conducts income tax audits under Section 177. Know how you can be selected for audit, what documents are needed, and how to respond effectively." $b

# PROFESSION BLOGS

# 13
$b = @'
<h2>Federal vs Provincial Agricultural Tax</h2><p>Agricultural income is exempt from federal income tax (FBR) under the Income Tax Ordinance 2001. However, each province levies its own provincial agricultural income tax if land exceeds specified area.</p><h2>Provincial Agricultural Income Tax Rates</h2><table><tr><th>Province</th><th>Minimum Land</th><th>Tax Rate</th></tr><tr><td>Punjab</td><td>Above 12.5 acres</td><td>Progressive slabs up to 15%</td></tr><tr><td>Sindh</td><td>Above 16 acres</td><td>Progressive slabs up to 15%</td></tr><tr><td>KPK</td><td>Above 5 acres</td><td>Flat rate per acre</td></tr></table><h2>When Farmers Need FBR Filing</h2><ul><li>If you have non-agricultural income (salary, rent, business) - must file federal return</li><li>If you want filer status to save WHT on property, banking, and vehicles</li><li>If you buy or sell property - filer gets 50% lower WHT rate</li></ul><div class='highlight-box'><p><strong>Farmer with property or business income?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - free consultation on your specific tax situation.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Does a farmer need NTN? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Not required for pure agricultural income but NTN helps farmers get filer status, open business bank accounts, and save WHT on property transactions.</div></div></div>
'@
MkTopic "tax-for-farmers-agriculture-pakistan" "Income Tax for Farmers and Agriculture in Pakistan 2026" "Agricultural income tax guide for farmers in Pakistan 2026. Federal tax exemption, provincial agricultural income tax, NTN for farmers, and how to declare farm income." "farmer tax Pakistan 2026, agricultural income tax Pakistan, NTN for farmers Pakistan" "Tax Guides" "fas fa-tractor" "6 min read" "Agricultural income is exempt from federal income tax in Pakistan but provincial agriculture income tax applies. Farmers with other income sources must file federal return." $b

# 14
$b = @'
<h2>Capital Gains Tax on Listed Shares 2026</h2><table><tr><th>Holding Period</th><th>CGT Rate</th></tr><tr><td>Less than 12 months</td><td>15%</td></tr><tr><td>12-24 months</td><td>12.5%</td></tr><tr><td>Over 24 months</td><td>0%</td></tr></table><h2>Dividend Income Tax</h2><table><tr><th>Status</th><th>Rate</th><th>Type</th></tr><tr><td>Filer</td><td>15%</td><td>Final tax</td></tr><tr><td>Non-filer</td><td>30%</td><td>Final tax</td></tr></table><h2>How to Declare Investments</h2><ul><li>Include share portfolio value in wealth statement at June 30 market value</li><li>Declare dividend income received during the year</li><li>Declare capital gains on shares sold</li><li>Claim NCCPL-deducted CGT as advance tax credit</li></ul><div class='highlight-box'><p><strong>Stock market investor?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - we declare your investments correctly and minimize tax liability.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>If I do not sell shares, do I still pay tax? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>No CGT if you do not sell. But dividend income from shares you hold is taxable at 15% (filer) when received. Include portfolio value in wealth statement regardless.</div></div></div>
'@
MkTopic "tax-for-stock-investors-pakistan-2026" "Tax for Stock Market Investors in Pakistan 2026 - CGT and Dividend Tax" "Income tax guide for stock market investors in Pakistan 2026. Capital gains tax on listed securities, dividend income tax, and how to declare investments in return." "stock market tax Pakistan 2026, capital gains tax shares Pakistan, dividend tax Pakistan" "Tax Guides" "fas fa-chart-line" "6 min read" "Stock market investors in Pakistan must declare all share transactions and dividend income. Capital gains on short-term trades are taxable while long-term gains are exempt." $b

# 15
$b = @'
<h2>Is YouTube Income Taxable in Pakistan?</h2><p>Yes. YouTube AdSense income, channel memberships, sponsorships, and brand deals are taxable as business income in Pakistan.</p><h2>Tax Treatment of YouTube AdSense</h2><ul><li>AdSense payments via bank - 1% WHT adjustable against annual tax</li><li>Annual income declared as freelance/business income</li><li>Applicable slab rates - 0% under Rs. 600K, then progressive rates</li><li>Expenses like equipment, internet, software are deductible</li></ul><h2>Steps for YouTube Tax Compliance</h2><ul><li>Register NTN as individual freelancer (Rs. 2,000)</li><li>Open business bank account to receive AdSense payments</li><li>Keep records of all income received monthly</li><li>File annual income tax return by September 30</li></ul><div class='highlight-box'><p><strong>Content creator in Pakistan?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - specialized freelancer and creator tax return from Rs. 3,500.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Do I need to register NTN as a YouTuber? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Yes if your annual AdSense income exceeds Rs. 600,000 or if you want filer status. Many banks now require NTN to receive international payments above certain limits.</div></div></div>
'@
MkTopic "tax-for-youtube-content-creators-pakistan-2026" "Tax for YouTube Content Creators in Pakistan 2026 - AdSense Income Tax" "Income tax guide for YouTube creators and influencers in Pakistan. AdSense income declaration, foreign remittance tax treatment, NTN registration, and FBR compliance." "YouTube tax Pakistan 2026, AdSense income tax Pakistan, content creator tax Pakistan" "Tax Guides" "fas fa-video" "6 min read" "YouTube AdSense income, sponsorships, and influencer fees are taxable in Pakistan. Register NTN, file annual return, and declare Google payments received via Pakistani banks." $b

# 16
$b = @'
<h2>Taxes at Every Property Investment Stage</h2><table><tr><th>Stage</th><th>Tax Applicable</th><th>Rate (Filer)</th></tr><tr><td>Buying property</td><td>WHT on purchase</td><td>3% of value</td></tr><tr><td>Holding property</td><td>Annual value tax (local)</td><td>Varies by council</td></tr><tr><td>Renting property</td><td>Income tax on rental</td><td>Slab rates after 20% deduction</td></tr><tr><td>Selling property</td><td>WHT + CGT</td><td>3% WHT + CGT on gain</td></tr></table><h2>Strategy - Minimize Property Tax</h2><ul><li>Hold for 5+ years to get 0% CGT</li><li>Be a filer - saves 50% on all WHT rates</li><li>Declare properties correctly in wealth statement</li><li>Deduct all legitimate expenses against rental income</li></ul><div class='highlight-box'><p><strong>Property investor?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - optimize your property tax strategy with our experts.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Can I offset property losses against other income? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Capital losses on property can be carried forward 3 years to offset future capital gains. They cannot be offset against salary or business income.</div></div></div>
'@
MkTopic "tax-for-property-investors-pakistan-2026" "Tax for Property Investors in Pakistan 2026 - Buy Sell and Rent Tax" "Complete tax guide for property investors in Pakistan 2026. Buying, selling, and renting property - CGT, WHT, rental income tax, and wealth statement requirements." "property investor tax Pakistan 2026, property sale tax Pakistan, rental income tax Pakistan" "Tax Guides" "fas fa-home" "7 min read" "Property investors in Pakistan face multiple taxes - WHT on purchase and sale, capital gains tax on profit, and rental income tax. Know all taxes before your next investment." $b

# 17
$b = @'
<h2>Transporter Tax Regime in Pakistan</h2><p>Transporters with goods vehicles are typically taxed under the presumptive tax regime (Section 234A) - a fixed annual tax per vehicle based on vehicle type and load capacity. This is final tax and simpler than normal income tax.</p><h2>Presumptive Tax Rates for Goods Vehicles 2026</h2><table><tr><th>Vehicle Type</th><th>Annual Tax</th></tr><tr><td>Up to 2,000 kg loading</td><td>Rs. 2,500</td></tr><tr><td>2,001 - 4,000 kg</td><td>Rs. 5,000</td></tr><tr><td>4,001 - 8,000 kg</td><td>Rs. 7,500</td></tr><tr><td>Over 8,000 kg</td><td>Rs. 12,500</td></tr></table><div class='highlight-box'><p><strong>Transporter or logistics company?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - NTN registration and annual return filing from Rs. 3,500.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Do I still need to file a return if I pay presumptive tax? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Yes. You still need to file an annual income tax return to be on ATL as active filer. The return will show presumptive tax paid as your full and final tax liability.</div></div></div>
'@
MkTopic "tax-for-transporters-pakistan-2026" "Tax for Transporters and Truck Owners in Pakistan 2026" "Income tax guide for transporters, truck owners, bus operators, and logistics companies in Pakistan 2026. Presumptive tax, NTN, and FBR compliance." "transporter tax Pakistan 2026, truck owner tax Pakistan, presumptive tax Pakistan" "Tax Guides" "fas fa-truck" "6 min read" "Transporters and truck owners in Pakistan are taxed under a presumptive tax regime. Fixed tax per vehicle. Know your obligations, NTN requirements, and compliance steps." $b

# 18
$b = @'
<h2>Taxes on Imports in Pakistan</h2><table><tr><th>Tax</th><th>Rate</th><th>Adjustable?</th></tr><tr><td>Customs Duty</td><td>Varies by HS code (0-30%)</td><td>No</td></tr><tr><td>Sales Tax at Import</td><td>18% standard</td><td>Yes (input credit)</td></tr><tr><td>Advance Income Tax</td><td>3-6% of import value</td><td>Yes</td></tr></table><h2>Import WHT for Filers vs Non-Filers</h2><ul><li>Filer advance income tax on import: 3% of import value</li><li>Non-filer advance income tax: 6% of import value</li><li>Both rates are adjustable against annual income tax return</li><li>Becoming a filer saves 3% on every import</li></ul><div class='highlight-box'><p><strong>Importer in Pakistan?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - specialized import tax compliance, WHT refund claims, and SRO applications.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>How do I claim refund of advance tax paid on imports? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Advance income tax on imports is adjustable. File your annual income tax return and claim all import WHT as advance tax. If total WHT exceeds tax liability, file a refund claim.</div></div></div>
'@
MkTopic "tax-consultant-importers-pakistan-2026" "Tax Consultant for Importers in Pakistan 2026 - WHT and Customs Guide" "Tax consultant for importers in Pakistan 2026. Withholding tax on imports, advance income tax, customs duty, sales tax, and FBR import compliance." "tax consultant importers Pakistan 2026, WHT on imports Pakistan, customs tax Pakistan" "Tax Guides" "fas fa-ship" "6 min read" "Importers in Pakistan face complex multi-layer taxation - customs duty, sales tax at import stage, advance income tax, and WHT. Expert tax guidance ensures compliance and refund claims." $b

# 19
$b = @'
<h2>WHT on Commission Income</h2><p>Under Section 233, the person paying commission must deduct WHT before paying the agent. This WHT is adjustable against annual income tax liability.</p><h2>Commission WHT Rates 2026</h2><table><tr><th>Type of Commission</th><th>Filer Rate</th><th>Non-Filer Rate</th></tr><tr><td>Advertising agents</td><td>10%</td><td>20%</td></tr><tr><td>Life insurance agents</td><td>8%</td><td>16%</td></tr><tr><td>General agents and brokers</td><td>12%</td><td>24%</td></tr><tr><td>Property dealers (commission)</td><td>10%</td><td>20%</td></tr></table><div class='highlight-box'><p><strong>Commission agent or broker?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - we file your return and claim back excess WHT.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Can I deduct expenses against commission income? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Yes. All genuine business expenses are deductible against commission income - travel, phone bills, office rent, marketing costs. Keep all receipts for FBR verification.</div></div></div>
'@
MkTopic "tax-for-commission-agents-pakistan" "Tax for Commission Agents in Pakistan 2026 - Commission Income Tax" "Income tax guide for commission agents, brokers, and agents in Pakistan 2026. WHT deducted on commissions, how to declare in return, and business registration." "commission agent tax Pakistan 2026, broker tax Pakistan, WHT on commission Pakistan" "Tax Guides" "fas fa-handshake" "6 min read" "Commission agents and brokers in Pakistan have WHT deducted on commissions received. This adjustable WHT must be declared in annual return. Know your tax obligations." $b

# 20
$b = @'
<h2>WHT on Contractor Payments</h2><p>Under Section 153, any company, AOP, or government body paying a contractor must deduct WHT before making payment. This WHT is adjustable against the contractor annual income tax return.</p><h2>Contractor WHT Rates 2026</h2><table><tr><th>Type</th><th>Filer Rate</th><th>Non-Filer Rate</th></tr><tr><td>Supply of goods</td><td>4%</td><td>8%</td></tr><tr><td>Services rendered</td><td>8%</td><td>16%</td></tr><tr><td>Execution of contracts</td><td>7%</td><td>14%</td></tr></table><h2>Why Contractors Must Be Filers</h2><ul><li>Non-filer pays double WHT on every contract</li><li>Government contracts require active filer status</li><li>Excess WHT refunded after filing annual return</li></ul><div class='highlight-box'><p><strong>Contractor or sub-contractor?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - NTN registration and annual return from Rs. 3,500. Recover your excess WHT.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>My client deducted 7% on my contract payment. Can I get it back? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Yes if your total tax liability is less than WHT deducted. File annual income tax return, declare all income, claim WHT credits, and FBR will refund the excess within 60 days.</div></div></div>
'@
MkTopic "tax-for-contractors-pakistan-2026" "Tax for Contractors and Sub-Contractors in Pakistan 2026" "Income tax guide for contractors and sub-contractors in Pakistan 2026. WHT on contract payments, Section 153 compliance, NTN registration, and annual return filing." "contractor tax Pakistan 2026, sub-contractor WHT Pakistan, Section 153 tax Pakistan" "Tax Guides" "fas fa-hard-hat" "6 min read" "Contractors in Pakistan have 7% WHT deducted on every payment received from companies and government. This is adjustable. File return to claim credits and maintain filer status." $b

# 21
$b = @'
<h2>Do Housewives Need to Pay Income Tax?</h2><p>No. If you have no personal income (salary, business, rent etc), you have no income tax liability. However, NTN registration and filing a nil return can be very beneficial.</p><h2>Benefits of NTN for Housewives</h2><ul><li><strong>Property transactions:</strong> Save 50% WHT when buying or selling property in your name</li><li><strong>Inheritance and gifts:</strong> Properly document inherited assets in your name</li><li><strong>Bank savings:</strong> Reduce bank profit WHT from 30% to 15%</li><li><strong>Business setup:</strong> If you start a business, you already have NTN</li></ul><h2>What to Declare in Nil Return</h2><ul><li>Assets in your name (property, vehicle, jewelry, bank balance)</li><li>Source of funds - husband income, inheritance, gift</li><li>No income to declare - file nil income return</li></ul><div class='highlight-box'><p><strong>Housewife wanting filer status?</strong> WhatsApp <a href='https://wa.me/923284675162' style='color:#14B8A6;font-weight:600'>0328-4675162</a> - NTN + nil return from Rs. 3,500. Start saving on property and bank transactions.</p></div><h2>Frequently Asked Questions</h2><div class='faq-list'><div class='faq-item'><div class='faq-q'>Can a housewife file her own separate tax return? <i class='fas fa-chevron-down'></i></div><div class='faq-a'>Yes. Every citizen can file a separate return. If assets are in your name, file your own return with nil income and declare assets funded by husband as gift from spouse - this is fully acceptable to FBR.</div></div></div>
'@
MkTopic "tax-for-housewives-homemakers-pakistan" "Tax for Housewives and Homemakers in Pakistan 2026" "Do housewives need to file tax in Pakistan? NTN for housewives, asset declaration, filer benefits on property, and wealth statement for homemakers." "housewife NTN Pakistan 2026, nil return Pakistan, filer status housewife Pakistan" "Tax Guides" "fas fa-house-user" "5 min read" "Housewives and homemakers without personal income do not pay income tax but may benefit from NTN registration for property transactions and filer status advantages." $b

Write-Host "Script C done. Created: $($script:created) | Skipped: $($script:skipped)"
